ARRAYS 1D PARTE 1: 


1. Crea un array_1 lleno ceros con una longitud de 8 elementos. 

In [3]:
import numpy as np

array1 = np.zeros(8)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0.]


2. Haz que todos los elementos de este array sean igual a 2 


In [6]:
import numpy as np

array1 = np.zeros(8)

array1[:] = 2;

print(array1)

[2. 2. 2. 2. 2. 2. 2. 2.]


3. Crea un array_2 que contenga todos los números pares del 1 al 10.


In [ ]:
import numpy as np

array2 = np.arange(2, 11, 2)

print(array2)

[ 2  4  6  8 10]


4. Suma todos los elementos del array_2 usando un bucle y después usando un método de numpy. Compara los resultados

In [4]:
import numpy as np

array2 = np.arange(2, 11, 2)

acum = 0
for number in array2:
    acum += number
suma_array = np.sum(array2)

print('Acumulador', acum)
print('funcion numpy', suma_array)


Acumulador 30
funcion numpy 30


5. Revierte array_2 y guárdalo en una variable independiente. 

In [ ]:
import numpy as np

array2 = np.arange(2, 11, 2)
array2_revertido =  array2[::-1]

print(array2_revertido)


[10  8  6  4  2]


6. Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y
array_2_revertido
 (Pista: Investiga el uso de intersect1d() de numpy

In [7]:
import numpy as np

array1 = np.zeros(8)
array1[:] = 2;

array2 = np.arange(2, 11, 2)
array2_revertido =  array2[::-1]

num_comun = np.intersect1d(np.intersect1d(array1, array2), np.intersect1d(array2, array2_revertido))

print(num_comun)

[2.]


7. Crea un arrays lleno de 1s con una longitud dada por el usuario


In [10]:
import numpy as np

size_array = int(input("introduce el tamñano que va a tener el array"))
array = np.ones(size_array)
print(array)


[1. 1. 1.]


ARRAYS 1D PARTE 2: 


1. Crea un array con 15 números enteros aleatorios entre 1 y 100


In [12]:
import numpy as np
size_array = 15

array = np.random.randint(1, 101, size = 15)
    
print(array)

[52 86 14 16 18 60 98 31 92 85 55 20 44 32 24]


2. Multiplica todos los elementos del array usando un bucle y después usando un
método de numpy. Compara los resultados


In [20]:
import numpy as np
size_array = 15

array = np.random.randint(1, 101, size = 15)
acum = float(1)
for number in array:
    acum = float(acum * number)

array = array.prod()
    
print('ACUMULADOR', acum)
print('ARRAY', array)

ACUMULADOR 1.639736061448969e+24
ARRAY 4980736926867480960


3. Crea otro array con 15 números decimales aleatorios entre 0 y 1


In [25]:
import numpy as np
array_uniform = np.random.uniform(0, 1, size=15)

print(array_uniform)

[0.69438842 0.93555978 0.61639753 0.45274433 0.17657261 0.81723768
 0.31582246 0.19502117 0.21176786 0.74224003 0.29243763 0.33419922
 0.03386487 0.50294332 0.56748854]


4. Suma los elementos de ambos arrays elementos por elemento. Resuélvelo usando un
operador y después con una función de numpy
 (Pista: busca en google que función de numpy hace esto)

In [ ]:
import numpy as np
size_array = 15

array = np.random.randint(1, 101, size = size_array)
array_uniform = np.random.uniform(0, 1, size = size_array)

print(float(array.sum()) + array_uniform.sum())




706
6.543609681097309
712.5436096810973


5. Ahora réstalos. Resuélvelo usando un operador y después con una función de numpy
(Pista: busca en google que función de numpy hace esto)

In [ ]:
import numpy as np
size_array = 15

array = np.random.randint(1, 101, size = size_array)
array_uniform = np.random.uniform(0, 1, size = size_array)

print(float(array.sum()) - array_uniform.sum())

8
837.1789758365715


6. Haz lo mismo con la multiplicación elemento por elemento. Usa un operador y
después con una función de numpy
 (Pista: busca en google que función de numpy hace esto)

In [36]:
import numpy as np
size_array = 15

array = np.random.randint(1, 101, size = size_array)
array_uniform = np.random.uniform(0, 1, size = size_array)

print(float(array.prod()) * array_uniform.prod())

-182600353063172.7


7. Encuentra el valor más alto del primer array que has creado. 


In [51]:
import numpy as np

array = np.random.randint(1, 101, size = size_array)

print(array.max())


99


8. Calcula la media (mean), la mediana (median) y al deviación estandar (standard
deviation) de los arrays (Nota: No nos importa el signicado matemático de estos
valores, lo importante es que encuentres que función de numpy necesitas. Puedes
hacer la búsqueda en castellano o en inglés, aunque en inglés muchas veces suele
haber más resultados).

In [52]:
import numpy as np 

array = np.random.randint(1, 101, size = 15)

print('MEDIA', array.mean())
print('MEDIANA', np.median(array))
print('STANDARD DEVIATION', array.std())

MEDIA 47.666666666666664
MEDIANA 38.0
STANDARD DEVIATION 17.76388345929897


ARRAYS 2D 


9. Crea un arrays lleno de 1s con una longitud dada por el usuario


In [56]:
import numpy as np
size_array = int(input('Dame un numero para la longitud del array'))
array = np.ones(size_array, dtype = 'float64')

print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]


10.Cambia la forma del array para que tenga una estructura de tipo (filas, columnas)


In [1]:
import numpy as np
col_array = int(input('Dame el numero de columnas'))
row_array = int(input('Dame el numero de filas'))
array = np.ones(row_array*col_array, dtype = 'float64')
print(array)

print(array.reshape(row_array, col_array))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


11.Crea una “matriz identidad” con la misma forma que el array anterior (las, columnas)


In [ ]:
import numpy as np
col_array = int(input('Dame el numero de columnas'))
row_array = int(input('Dame el numero de filas'))
array = np.eye(row_array, col_array)
print(array)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


12.Concatena ambas estructuras horizontalmente y verticalmente
 (Pista: Investiga el funcionamiento de concatenate() y de vstack() y hstack() de numpy)

In [ ]:
import numpy as np
