CALCULO DE NOTAS FINALES

Supongamos que tienes un conjunto de calificaciones de un grupo de estudiantes en un
curso. Cada estudiante tiene cuatro calicaciones: dos exámenes, un trabajo nal y una
participación en clase. Quieres calcular la nota nal de cada estudiante, donde los
exámenes valen un 30% cada uno, el trabajo nal vale un 30% y la participación en clase
vale un 10%. Para ello, puedes usar NumPy para crear un array de 4 columnas y n las,
donde n es el número de estudiantes. Cada columna representa una de las calicaciones
y cada la representa un estudiante. Luego, puedes usar operaciones de NumPy para
calcular la nota nal de cada estudiante y almacenarla en un nuevo array de una sola
columna.

In [63]:
import numpy as np

#definicion de variables
col = 4
i = 1
n_estudiantes = int(input('Introduce el numero de estudiantes'))

arr_notas = np.empty((0, col), dtype=int)

# Crear las notas de los estudiantes
for _ in range(n_estudiantes):
    new_row = np.random.randint(0, 11, col)  # Generar una fila con 4 calificaciones
    arr_notas = np.vstack([arr_notas, new_row])

print('Las notas de los alumnos', arr_notas)


#Se realizarán las operaciones necesarias.
notas_medias = np.array([0.3, 0.3, 0.3, 0.1])
notas_finales = np.dot(arr_notas, notas_medias)
print('Notas finales: ', notas_finales)

Las notas de los alumnos [[7 8 5 5]
 [9 5 8 4]
 [8 0 1 5]
 [3 6 2 4]]
Notas finales:  [6.5 7.  3.2 3.7]


In [38]:
# Array de escalares para cada fila
escalares = np.array([1, 2, 3])
array = np.array([[1,2,3], [1,2,4], [1,2,5]])
# Multiplicar cada fila por su respectivo escalar
array_escalado_filas = array * escalares[:, np.newaxis]
print("Array con filas escaladas:\n", array_escalado_filas)


Array con filas escaladas:
 [[ 1  2  3]
 [ 2  4  8]
 [ 3  6 15]]


ANALISIS DE DATOS - VENTAS POR MES

Supongamos que tienes un conjunto de datos de ventas de una tienda durante un año.
Cada la representa una venta y tiene tres columnas: la fecha de la venta, el monto de la
venta y la categoría de producto vendido (por ejemplo, electrónicos, ropa, alimentos,
etc.). Quieres analizar estos datos para determinar cuánto fue el monto total de ventas en
cada mes. Para ello, puedes usar NumPy para cargar los datos en un array de 3
columnas y n las, donde n es el número de ventas. Luego, puedes usar operaciones de
NumPy para ltrar los datos por mes y sumar los montos de venta correspondientes.

In [ ]:
import numpy as np

# Datos de ventas de la tienda
ventas = np.array([
    ['2022-01-01', 100, 'ropa'],
    ['2022-01-02', 200, 'alimentos'],
    ['2022-01-03', 150, 'ropa'],
    ['2022-02-01', 120, 'alimentos'],
    ['2022-02-02', 180, 'electrónicos'],
    ['2022-02-03', 200, 'alimentos'],
    ['2022-03-01', 90, 'ropa'],
    ['2022-03-02', 110, 'electrónicos'],
    ['2022-03-03', 100, 'alimentos']
])

#Extraer las fechas
fechas = np.array([venta[0] for venta in ventas])

#Extraemos el mes
meses = np.array([int(fecha[5:7]) for fecha in fechas])

montos_mes = np.zeros((12))

for mes in range(1, 13):
    ventas_mes = ventas[meses == mes]
    montos_mes[mes - 1] = np.sum(ventas_mes[:,1].astype(int))
print('TOTAL DE VENTAS POR MES', montos_mes)


[1 1 1 2 2 2 3 3 3]
TOTAL DE VENYAS POR MES [450. 500. 300.   0.   0.   0.   0.   0.   0.   0.   0.   0.]




ANALISIS DE DATOS CLIMÁTICOS


Supongamos que tienes un conjunto de datos de clima que contiene información sobre la
temperatura, la humedad y la presión atmosférica en una ciudad durante un año. Quieres
analizar estos datos para determinar cuál fue la temperatura promedio de cada mes, cuál
fue la humedad promedio y la presión atmosférica promedio durante todo el año. Para
ello, puedes usar NumPy para cargar los datos en un array de 3 columnas y n filas, donde
n es el número de mediciones. Luego, puedes usar operaciones de NumPy para filtrar los
datos por mes y calcular las medias de temperatura, humedad y presión atmosférica
correspondientes.

In [10]:
import numpy as np

# Datos de clima
clima = np.array([
    [20, 70, 1009, 1],
    [21, 60, 1011, 1],
    [22, 40, 1010, 1],
    [18, 75, 1012, 2],
    [21, 60, 1008, 3],
    [22, 65, 1008, 3],
    [25, 60, 1010, 4],
    [27, 49, 1007, 5],
    [29, 45, 1007, 5],
    [28, 50, 1007, 5],
    [30, 45, 1005, 6],
    [30, 45, 1005, 6],
    [32, 40, 1002, 7],
    [33, 35, 1003, 8],
    [31, 45, 1003, 9],
    [29, 42, 1002, 9],
    [29, 42, 1002, 9],
    [35, 43, 1003, 9],
    [28, 50, 1006, 10],
    [25, 60, 1010, 11],
    [27, 59, 1012, 11],
    [24, 58, 1011, 11],
    [22, 70, 1011, 12]


])

meses = clima[:,3]
temperaturas = clima[:,0]
humedades = clima[:,1]
presiones= clima[:,2]
temp_mes = np.zeros(12)
hum_mes = np.zeros(12)
pres_mes = np.zeros(12)


for i in range(12):
    temp_mes[i] = np.mean(temperaturas[meses == i + 1])
    hum_mes[i] = np.mean(humedades[meses == i + 1])
    pres_mes[i] = np.mean(presiones[meses == i + 1])


print("Las temperaturas medias por mes son:", temp_mes)
print("Las humedades medias por mes son:", hum_mes)
print("Las presiones atmosfericas medias por mes son:", pres_mes)
    



Las temperaturas medias por mes son: [21.         18.         21.5        25.         28.         30.
 32.         33.         31.         28.         25.33333333 22.        ]
Las humedades medias por mes son: [56.66666667 75.         62.5        60.         48.         45.
 40.         35.         43.         50.         59.         70.        ]
Las presiones atmosfericas medias por mes son: [1010.  1012.  1008.  1010.  1007.  1005.  1002.  1003.  1002.5 1006.
 1011.  1011. ]
